# Generated by Django 4.1.4 on 2022-12-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='categoty',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(
                blank=True, upload_to='recipes/image/%Y/%m'),
        ),
    ]
